name: Update OpenSauced Dev Card

on:
  schedule:
    - cron: '0 0 * * 0' # Run once a week on Sunday at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dev-card:
    runs-on: ubuntu-latest
    steps:
      - name: Update Dev Card
        uses: nickytonline/open-sauced-dev-card-action@v1.1.0
        with:
          github-token: ${{ secrets.TOKEN }}
          username: 'GearHead87'
          
